config/routes.rb
Rails.application.routes.draw do
  root 'animals#index'
  resources :animals, only: %i[index show new edit create update] do
    resources :adoptions, only: %i[index new create]
  end
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :animal
  validates :adopter_name, presence: true, length: { minimum: 3 }
  validates :adoption_date, presence: true
  validates :animal, presence: true
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :animal_type
  has_one :adoption
  has_one_attached :photo
  validates :name, presence: true, length: { minimum: 2 }
  validates :animal_type, presence: true
  validates :date_of_birth, presence: true

  scope :available_for_adoption, -> {
    includes(:adoption).where(adoptions: { animal_id: nil })
  }
end

app/models/animal_type.rb
class AnimalType < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  def index
    redirect_to animals_path
  end

  def new
    @adoption = Adoption.new
  end

  def create
    @adoption = Adoption.new(adoption_params)
    @adoption.animal_id = params[:animal_id]

    if @adoption.save
      redirect_to animals_path, notice: 'Pet was successfully marked as adopted'
    else
      render :new
    end
  end

  def adoption_params
    params.require(:adoption).permit(:adopter_name, :adoption_date, :animal_id)
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[show edit update]

  def index
    @animals = Animal
      .available_for_adoption
      .order(created_at: :desc)
  end

  def show; end

  def new
    @animal = Animal.new
  end

  def edit; end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      redirect_to animals_path, notice: 'Pet was successfully added'
    else
      render :new
    end
  end

  def update
    if @animal.update(animal_params)
      redirect_to animals_path, notice: 'Pet was successfully updated'
    else
      render :edit
    end
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:name, :date_of_birth, :animal_type_id, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adoptions/new.html.erb
<%- content_for(:page_title, 'Mark as adopted') %>
<h1>Mark pet as adopted</h1>
<br>
<%= form_with model: @adoption, local: true, url: animal_adoptions_path do |f| %>
  <% if @adoption.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@adoption.errors.count, "error") %>:
      </h4>
      <ul>
        <% @adoption.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-8">
      <div class="form-group">
        <%= f.label :adopter_name %><br/>
        <%= f.text_field :adopter_name, class: 'form-control' %>
      </div>
    </div>
    <div class="col-4">
      <div class="form-group">
        <%= f.label :adoption_date %><br/>
        <%= f.date_field :adoption_date, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= link_to 'Back', animals_path, class: 'btn btn-secondary' %>
  <%= f.submit 'Mark as adopted', class: 'btn btn-success' %>
<% end %>

app/views/animals/_form.html.erb
<%= form_with model: @animal, local: true do |f| %>
  <% if @animal.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@animal.errors.count, "error") %>:
      </h4>
      <ul>
        <% @animal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="row">
    <div
      id="animal-image-preview-container"
      class="col-sm-4"
      style="<%= 'display: none;' unless @animal.photo.attached? %>"
    >
      <% if @animal.photo.attached? %>
        <%= image_tag @animal.photo,
          id: 'animal-image-preview',
          class: 'card-img-top animal-image' %>
      <% else %>
          <img id="animal-image-preview" class="card-img-top animal-image" src="#">
      <% end %>
    </div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label @animal.new_record? ? 'Add photo' : 'Edit photo' %><br>
        <%= f.file_field :photo, accept:'image/*' %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-8">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="col-4">
      <div class="form-group">
        <%= f.label :animal_type_id %>
        <%= f.collection_select :animal_type_id,
                                AnimalType.all,
                                :id,
                                :name,
                                {},
                                {class: 'form-control'} %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="form-group">
        <%= f.label :date_of_birth %>
        <%= f.date_field :date_of_birth, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= link_to 'Back', animals_path, class: 'btn btn-secondary' %>
  <%= f.submit 'Save pet', class: 'btn btn-success' %>
<% end %>
<%= javascript_pack_tag 'animal' %>

app/views/animals/edit.html.erb
<%- content_for(:page_title, 'Edit pet') %>

<h1>Edit pet</h1>

<%= render 'form' %>

app/views/animals/index.html.erb
<%- content_for(:page_title, 'Pets for adoption') %>
<h1>Pets for adoption</h1>
<ul id="animals-list">
  <% @animals.each do |animal| %>
    <li class="animal-item">
      <div class="card">
        <% if animal.photo.attached? %>
          <%= link_to animal_path(animal) do %>
            <%= image_tag animal.photo, class: 'card-img-top animal-image' %>
          <% end %>
        <% end %>
        <div class="card-body animal-container">
          <%= link_to animal_path(animal) do %>
            <h5 class="card-title"><%= animal.name %></h5>
            <h6 class="card-subtitle text-muted"><%= animal.animal_type.name %></h6>
          <% end %>
          <div class="animal-actions">
            <%= link_to 'Mark as adopted', new_animal_adoption_path(animal), class: 'btn btn-success' %>
            <%= link_to 'Edit', edit_animal_path(animal), class: 'btn btn-info' %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/animals/new.html.erb
<%- content_for(:page_title, 'New pet') %>

<h1>Add new pet</h1>

<%= render 'form' %>

app/views/animals/show.html.erb
<%- content_for(:page_title, 'Pet details') %>
<div class="card">
  <div class="card-body animal-detail">
    <% if @animal.photo.attached? %>
      <%= image_tag @animal.photo, class: 'card-img-top animal-image' %>
    <% end %>
    <div class="animal-info">
      <div class="card-title"><h1><%= @animal.name %></h1></div>
      <div class="card-subtitle text-muted"><%= @animal.animal_type.name %></div>
      <% if @animal.date_of_birth.respond_to?(:strftime) %>
        <p>Born in <%= @animal.date_of_birth.strftime('%m/%d/%Y') %>
      <% end %>
    </div>
  </div>
</div>
<br>
<%= link_to 'Back', animals_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title><%= content_for(:page_title) || 'Adopt a Pet'%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Adopt a Pet</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarCollapse"
        aria-controls="navbarCollapse"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Pets for adoption', animals_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Add new pet', new_animal_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <main class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-success">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <%= javascript_pack_tag 'custom' %>
  </body>
</html>